#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the hourglassSum function below.
def hourglassSum(arr,row,column):
    sum = 0
    sum += arr[i][j]
    sum += arr[i-1][j-1]
    sum += arr[i-1][j]
    sum += arr[i-1][j+1]
    sum += arr[i+1][j-1]
    sum += arr[i+1][j]
    sum += arr[i+1][j+1]

    return sum



if __name__ == '__main__':

    arr = []

    for _ in range(6):
        arr.append(list(map(int, input().rstrip().split())))

maxsum = -63
for i in range(1,5):
    for j in range(1,5):
        currentsum = hourglassSum(arr,i,j)
        if currentsum > maxsum:
            maxsum = currentsum
print(maxsum)


