#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the minimumSwaps function below.
def minimumSwaps(n,arr):
    ref_arr = sorted(arr)
    index_dict = {v:i for i,v in enumerate(arr)}
    swaps = 0
    for i,v in enumerate(arr):
        correct_value = ref_arr[i]
        if v != correct_value:
            temp = index_dict[correct_value]
            arr[temp],arr[i] = arr[i],arr[temp]
            index_dict[v] = temp
            index_dict[correct_value] = i
            swaps += 1
    return swaps
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    res = minimumSwaps(n,arr)

    fptr.write(str(res) + '\n')

    fptr.close()
